# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'sinatra'
gem 'activerecord', '=4.2.10'
gem 'mini_record'
gem 'sqlite3', '~> 1.3.6'
